spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/jwt_demo
    username: postgres
    password: 5432
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


## App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000